name: Backend CI

on:
  push:
    branches: [ "main", "ci-cd", "develop" ] # <-- Añadidas tus ramas de trabajo
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    name: Build Spring Boot and Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Compilar con Maven
        working-directory: ./backend
        run: mvn clean package -DskipTests

      - name: Construir imagen de Docker
        working-directory: ./backend
        run: docker build -t fitcloud-backend:latest .