name: Frontend CI

on:
  push:
    branches: [ "main", "ci-cd", "develop" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    name: Build React Vite Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'

      - name: Activar Corepack
        run: corepack enable

      - name: Instalar dependencias
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Compilar frontend
        working-directory: ./frontend
        run: pnpm run build